In [20]:
# menambahkan pustaka yang diperlukan
from sklearn import datasets
from sklearn import model_selection
from sklearn.metrics import accuracy_score
import numpy as np
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#array untuk menampilkan hasil klasifikasi
flower = ['Iris-Setosa', 'Iris-versiColor', 'Iris-Virginica']

# mengambil sample dataset bunga iris yang disediakan tensorflow 
iris=datasets.load_iris()
X = iris.data
Y = iris.target
y = tensorflow.keras.utils.to_categorical(Y)

# proses ini membagi dataset menjadi 2, data training dan dataset...
# test_size = menyatakan seberapa porsi untuk test dan train
crossValidation = model_selection.KFold(n_splits=10, random_state=14, shuffle=True)

# cetak sample fitur data iris 
print("input")
print(X)
# cetak klasifikasi fitur
print("output")
print(Y)

input
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 

In [21]:
# membuat model Neural Network
model = Sequential()
# membuat layer input dengan 4 masukan data fitur, 8 neuron, dan fungsi aktivasi relu
# sepal length, sepal width, petal length, petal width
model.add(Dense(8, input_dim=4, activation='relu'))
# membuat layer hidden dengan 8 neuron
model.add(Dense(8, activation='relu'))
# membuat layer output dengan 3 output klasifikasi (setosa, versicolor, virginica), dan fungsi aktivasi softmax
model.add(Dense(3, activation='softmax'))
# melakukan kompilasi model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# melakukan proses training data sample
model.fit(X,y, batch_size=5, epochs=50, verbose=2)
# melakukan penyimpanan hasil training
model.save('iris.h5')
# mencetak desain model Neural Network
print(model.summary())
# mendapatkan nilai bobot
print(model.get_weights())


Epoch 1/50
30/30 - 2s - loss: 1.0672 - accuracy: 0.3333 - 2s/epoch - 59ms/step
Epoch 2/50
30/30 - 0s - loss: 0.9302 - accuracy: 0.3533 - 96ms/epoch - 3ms/step
Epoch 3/50
30/30 - 0s - loss: 0.8228 - accuracy: 0.6400 - 112ms/epoch - 4ms/step
Epoch 4/50
30/30 - 0s - loss: 0.7598 - accuracy: 0.6667 - 109ms/epoch - 4ms/step
Epoch 5/50
30/30 - 0s - loss: 0.7075 - accuracy: 0.7133 - 115ms/epoch - 4ms/step
Epoch 6/50
30/30 - 0s - loss: 0.6592 - accuracy: 0.6733 - 114ms/epoch - 4ms/step
Epoch 7/50
30/30 - 0s - loss: 0.6124 - accuracy: 0.7267 - 120ms/epoch - 4ms/step
Epoch 8/50
30/30 - 0s - loss: 0.5737 - accuracy: 0.8267 - 138ms/epoch - 5ms/step
Epoch 9/50
30/30 - 0s - loss: 0.5352 - accuracy: 0.8467 - 136ms/epoch - 5ms/step
Epoch 10/50
30/30 - 0s - loss: 0.5093 - accuracy: 0.8400 - 117ms/epoch - 4ms/step
Epoch 11/50
30/30 - 0s - loss: 0.4826 - accuracy: 0.8467 - 189ms/epoch - 6ms/step
Epoch 12/50
30/30 - 0s - loss: 0.4603 - accuracy: 0.8933 - 120ms/epoch - 4ms/step
Epoch 13/50
30/30 - 0s - los

In [23]:
# melakukan prediksi pada sample data tes Iris-Setosa
dataTes = [[5.1, 3.5, 1.4, 0.2]]
prediction = model.predict(dataTes)
print(prediction)
pos_indext_nilai_max = np.array(prediction).argmax()
print(pos_indext_nilai_max)
print("Bunga ini diklasifikasikan sebagai : ")
print(flower[pos_indext_nilai_max])

1/1 [==============================] - 0s 128ms/step
[[9.9729127e-01 2.6944419e-03 1.4300168e-05]]
0
Bunga ini diklasifikasikan sebagai : 
Iris-Setosa
